## MariaDB instance bound to port 3307 on the host. Data is persisted.
## PhpMyAdmin instance bound to port 8000. Use root as user and password.

version: '3.1'

services:
  db:
    image: mariadb:10.9.3
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ohmyclass
    volumes:
      - db:/var/lib/mysql
    command: --init-file ./data/application/ohmyclass-init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST:mariadb
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db:
